image: python:3.10

stages:
  - test
  - stress

functional_test:
  stage: test
  script:
    - pip install pandas numpy || true
    - python IMPLEMENTATION/pcb_one_click/demo.py > result.txt
  artifacts:
    paths:
      - result.txt



stress_causal_safety:
  stage: stress
  script:
    - pip install pandas numpy
    - python IMPLEMENTATION/pcb_one_click/stress_test/stress_test_causal_safety2.py
  artifacts:
    when: always
    paths:
      - stress_result.txt


causal_stability:
  stage: test
  script:
    - pip install pandas numpy || true
    - python IMPLEMENTATION/pcb_one_click/stress_test/stress_test_causal_stability.py > stability_result.txt
  artifacts:
    paths:
      - stability_result.txt
  allow_failure: false