image: python:3.10

stages:
  - test
  

functional_test:
  stage: test
  script:
    - pip install pandas numpy || true
    - python IMPLEMENTATION/pcb_one_click/demo.py > result.txt
  artifacts:
    paths:
      - result.txt
