image: python:3.10

stages:
  - test
  - stress

functional_test:
  stage: test
  script:
    - pip install pandas numpy || true
    - python IMPLEMENTATION/pcb_one_click/demo.py > result.txt
  artifacts:
    paths:
      - result.txt

stress_tests:
  stage: stress
  script:
    - pip install pandas numpy || true
    - python IMPLEMENTATION/pcb_one_click/stress_test_causal_safety.py > stress_result.txt
  artifacts:
    paths:
      - stress_result.txt
